auth:
  consumer_key: "XWQVjrtDw0fOBeIWsJqyQ"
  consumer_secret: "7oEyZUPXzWA6telPELxkMQ2FAdcL7eKKr2KpeJAkc"
  access_token_key: "945295926-0KEeZqRIHIDTNhI7v7WSKJH2SnTRXE2rx7P21xwS"
  access_token_secret: "CLPFgzz5ie2dvRu5a2kCN1TnhQ8XgJDg6UASH7pxMjg"
